sudo: false
language: ruby
cache: bundler
services:
  - postgresql
before_install:
  - gem install bundler
rvm:
  - 2.5.1
script:
  - bundle
  - bundle exec rails db:setup
  - bundle exec rspec
  - rubocop
