sudo: false
language: ruby
cache: bundler
services:
  - postgresql
before_install:
  - gem install bundler
  - gem install rubocop
rvm:
  - 2.5.1
script:
  - bundle
  - rails db:setup
  - rspec
  - rubocop
